/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.DanhMucBean;
import controller.ChuyenManHinhController;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author CLAY
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    public MainJFrame() {
        initComponents();
        
        //Hiển thị tên cho phần mềm
        setTitle("QUẢN LÝ KHÁCH SẠN");
        
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setView(jpnTrangChu,jlbTrangChu);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChu",jpnTrangChu,jlbTrangChu));
        listItem.add(new DanhMucBean("QuanLyKhachHang",jpnQuanLyKhachHang,jlbQuanLyKhachHang));
        listItem.add(new DanhMucBean("QuanLyNhanVien",jpnQuanLyNhanVien,jlbQuanLyNhanVien));
        listItem.add(new DanhMucBean("DatPhongTruoc",jpnDatPhongTruoc,jlbDatPhongTruoc));
        listItem.add(new DanhMucBean("ThuePhong",jpnThuePhong,jlbThuePhong));
        listItem.add(new DanhMucBean("DichVu",jpnDichVu,jlbDichVu));
        listItem.add(new DanhMucBean("InHoaDon",jpnInHoaDon,jlbInHoaDon));
        listItem.add(new DanhMucBean("ThongKeDoanhSo",jpnThongKeDoanhSo,jlbThongKeDoanhSo));
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnQuanLyKhachHang = new javax.swing.JPanel();
        jlbQuanLyKhachHang = new javax.swing.JLabel();
        jpnQuanLyNhanVien = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlbQuanLyNhanVien = new javax.swing.JLabel();
        jpnDatPhongTruoc = new javax.swing.JPanel();
        jlbDatPhongTruoc = new javax.swing.JLabel();
        jpnThuePhong = new javax.swing.JPanel();
        jlbThuePhong = new javax.swing.JLabel();
        jpnDichVu = new javax.swing.JPanel();
        jlbDichVu = new javax.swing.JLabel();
        jpnThongKeDoanhSo = new javax.swing.JPanel();
        jpnInHoaDon = new javax.swing.JPanel();
        jlbInHoaDon = new javax.swing.JLabel();
        jpnTrangChu = new javax.swing.JPanel();
        jlbTrangChu = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();
        jlbThongKeDoanhSo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(51, 51, 51));

        jpnQuanLyKhachHang.setBackground(new java.awt.Color(153, 153, 153));

        jlbQuanLyKhachHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbQuanLyKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbQuanLyKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbQuanLyKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_khachhang.png"))); // NOI18N
        jlbQuanLyKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout jpnQuanLyKhachHangLayout = new javax.swing.GroupLayout(jpnQuanLyKhachHang);
        jpnQuanLyKhachHang.setLayout(jpnQuanLyKhachHangLayout);
        jpnQuanLyKhachHangLayout.setHorizontalGroup(
            jpnQuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbQuanLyKhachHang)
                .addGap(32, 32, 32))
        );
        jpnQuanLyKhachHangLayout.setVerticalGroup(
            jpnQuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQuanLyNhanVien.setBackground(new java.awt.Color(102, 255, 102));

        jlbQuanLyNhanVien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_nhavien.png"))); // NOI18N
        jlbQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout jpnQuanLyNhanVienLayout = new javax.swing.GroupLayout(jpnQuanLyNhanVien);
        jpnQuanLyNhanVien.setLayout(jpnQuanLyNhanVienLayout);
        jpnQuanLyNhanVienLayout.setHorizontalGroup(
            jpnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyNhanVienLayout.createSequentialGroup()
                .addGroup(jpnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLyNhanVienLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel2))
                    .addGroup(jpnQuanLyNhanVienLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlbQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQuanLyNhanVienLayout.setVerticalGroup(
            jpnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbQuanLyNhanVien)
                .addGap(26, 26, 26))
        );

        jpnDatPhongTruoc.setBackground(new java.awt.Color(0, 204, 204));

        jlbDatPhongTruoc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbDatPhongTruoc.setForeground(new java.awt.Color(255, 255, 255));
        jlbDatPhongTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_datphongtruoc.png"))); // NOI18N
        jlbDatPhongTruoc.setText("ĐẶT PHÒNG TRƯỚC");

        javax.swing.GroupLayout jpnDatPhongTruocLayout = new javax.swing.GroupLayout(jpnDatPhongTruoc);
        jpnDatPhongTruoc.setLayout(jpnDatPhongTruocLayout);
        jpnDatPhongTruocLayout.setHorizontalGroup(
            jpnDatPhongTruocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDatPhongTruocLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jlbDatPhongTruoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDatPhongTruocLayout.setVerticalGroup(
            jpnDatPhongTruocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDatPhongTruocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDatPhongTruoc)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpnThuePhong.setBackground(new java.awt.Color(204, 204, 0));

        jlbThuePhong.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbThuePhong.setForeground(new java.awt.Color(255, 255, 255));
        jlbThuePhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_thuephong.png"))); // NOI18N
        jlbThuePhong.setText("THUÊ PHÒNG ");

        javax.swing.GroupLayout jpnThuePhongLayout = new javax.swing.GroupLayout(jpnThuePhong);
        jpnThuePhong.setLayout(jpnThuePhongLayout);
        jpnThuePhongLayout.setHorizontalGroup(
            jpnThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThuePhongLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jlbThuePhong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnThuePhongLayout.setVerticalGroup(
            jpnThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThuePhongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbThuePhong)
                .addGap(22, 22, 22))
        );

        jpnDichVu.setBackground(new java.awt.Color(153, 0, 153));

        jlbDichVu.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jlbDichVu.setForeground(new java.awt.Color(255, 255, 255));
        jlbDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dichvu.png"))); // NOI18N
        jlbDichVu.setText("DỊCH VỤ");

        javax.swing.GroupLayout jpnDichVuLayout = new javax.swing.GroupLayout(jpnDichVu);
        jpnDichVu.setLayout(jpnDichVuLayout);
        jpnDichVuLayout.setHorizontalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDichVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jpnDichVuLayout.setVerticalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDichVuLayout.createSequentialGroup()
                .addComponent(jlbDichVu)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jpnThongKeDoanhSo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpnThongKeDoanhSoLayout = new javax.swing.GroupLayout(jpnThongKeDoanhSo);
        jpnThongKeDoanhSo.setLayout(jpnThongKeDoanhSoLayout);
        jpnThongKeDoanhSoLayout.setHorizontalGroup(
            jpnThongKeDoanhSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnThongKeDoanhSoLayout.setVerticalGroup(
            jpnThongKeDoanhSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jpnInHoaDon.setBackground(new java.awt.Color(102, 102, 0));

        jlbInHoaDon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbInHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbInHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_hoadon.png"))); // NOI18N
        jlbInHoaDon.setText("IN HÓA ĐƠN");

        javax.swing.GroupLayout jpnInHoaDonLayout = new javax.swing.GroupLayout(jpnInHoaDon);
        jpnInHoaDon.setLayout(jpnInHoaDonLayout);
        jpnInHoaDonLayout.setHorizontalGroup(
            jpnInHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInHoaDonLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jlbInHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnInHoaDonLayout.setVerticalGroup(
            jpnInHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbInHoaDon)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jpnTrangChu.setBackground(new java.awt.Color(255, 0, 51));

        jlbTrangChu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jlbTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_manhinhchinh.png"))); // NOI18N
        jlbTrangChu.setText("TRANG CHỦ");

        javax.swing.GroupLayout jpnTrangChuLayout = new javax.swing.GroupLayout(jpnTrangChu);
        jpnTrangChu.setLayout(jpnTrangChuLayout);
        jpnTrangChuLayout.setHorizontalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrangChuLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jlbTrangChu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTrangChuLayout.setVerticalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTrangChu)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDatPhongTruoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThuePhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThongKeDoanhSo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnInHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jpnQuanLyKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnDatPhongTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnThongKeDoanhSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );

        jlbThongKeDoanhSo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbThongKeDoanhSo.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKeDoanhSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_thongke.png"))); // NOI18N
        jlbThongKeDoanhSo.setText("THỐNG KÊ DOANH SỐ");

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                        .addComponent(jlbThongKeDoanhSo)
                        .addGap(34, 34, 34)))
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbThongKeDoanhSo)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//hiển thị cái form ra màn hình
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

//tạo ra mấy cái panel
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbDatPhongTruoc;
    private javax.swing.JLabel jlbDichVu;
    private javax.swing.JLabel jlbInHoaDon;
    private javax.swing.JLabel jlbQuanLyKhachHang;
    private javax.swing.JLabel jlbQuanLyNhanVien;
    private javax.swing.JLabel jlbThongKeDoanhSo;
    private javax.swing.JLabel jlbThuePhong;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JPanel jpnDatPhongTruoc;
    private javax.swing.JPanel jpnDichVu;
    private javax.swing.JPanel jpnInHoaDon;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnQuanLyKhachHang;
    private javax.swing.JPanel jpnQuanLyNhanVien;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnThongKeDoanhSo;
    private javax.swing.JPanel jpnThuePhong;
    private javax.swing.JPanel jpnTrangChu;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
